fileVersion: 1
id: "7"
mappingDefinitions:
  ASSIGNMENT:
    database: DEV_NAVEENA
    schema: PUBLIC
  SRC:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
name: Production
type: Environment
